"""create all menu tables

Revision ID: 575528e0e509
Revises: 34cdd380fc81
Create Date: 2025-09-09 06:27:15.641338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575528e0e509'
down_revision: Union[str, Sequence[str], None] = '34cdd380fc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_categories_id'), 'menu_categories', ['id'], unique=False)
    op.create_table('menu_items_combos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_combos_id'), 'menu_items_combos', ['id'], unique=False)
    op.create_table('menu_items_combo_links',
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['menu_items_combos.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('combo_id', 'menu_item_id')
    )
    op.create_table('menu_items_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_images_id'), 'menu_items_images', ['id'], unique=False)
    op.create_table('menu_items_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('menu_size_name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_variants_id'), 'menu_items_variants', ['id'], unique=False)
    op.create_table('menu_items_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_variant_id', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_variant_id'], ['menu_items_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_discounts_id'), 'menu_items_discounts', ['id'], unique=False)
    op.add_column('menu_items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('menu_items', sa.Column('status', sa.Boolean(), nullable=False))
    op.alter_column('menu_items', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('ix_menu_items_price'), table_name='menu_items')
    op.create_foreign_key(None, 'menu_items', 'menu_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_index(op.f('ix_menu_items_price'), 'menu_items', ['price'], unique=True)
    op.alter_column('menu_items', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('menu_items', 'status')
    op.drop_column('menu_items', 'category_id')
    op.drop_index(op.f('ix_menu_items_discounts_id'), table_name='menu_items_discounts')
    op.drop_table('menu_items_discounts')
    op.drop_index(op.f('ix_menu_items_variants_id'), table_name='menu_items_variants')
    op.drop_table('menu_items_variants')
    op.drop_index(op.f('ix_menu_items_images_id'), table_name='menu_items_images')
    op.drop_table('menu_items_images')
    op.drop_table('menu_items_combo_links')
    op.drop_index(op.f('ix_menu_items_combos_id'), table_name='menu_items_combos')
    op.drop_table('menu_items_combos')
    op.drop_index(op.f('ix_menu_categories_id'), table_name='menu_categories')
    op.drop_table('menu_categories')
    # ### end Alembic commands ###
