services:
  menu-service:
    build: .
    env_file: .env
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: cassandra:4.1
    container_name: cassandra-db
    environment:
      CASSANDRA_CLUSTER_NAME: "MenuCluster"
      CASSANDRA_NUM_TOKENS: 16
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
