services:
  database:
    image: postgres:16
    container_name: reservation_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_db
    
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  reservation-service: 
    build: .
    container_name: reservation-service
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
        DATABASE_URL: postgres://postgres:postgres@database:5432/reservation_db
        JWT_SECRET: supersecret
    command: ["npm", "run", "dev"]


volumes:
  db_data:
