services:
  database:
    image: postgres:16
    container_name: authentication-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  authentication-service:
    build: .
    container_name: authentication-service
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5001"
      - "5555:5555"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/authentication_db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev


volumes:
  db_data:
